defaults: &defaults
  working_directory: ~/laravel

version: 2

jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    <<: *defaults
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: touch storage/testing.sqlite
      - run: touch database/database.sqlite
      - run: cp .env.testing .env
      - run: php artisan migrate --env=testing --database=sqlite --force
      - run: php artisan db:seed --env=testing --database=sqlite --force
      - run: cat database/database.sqlite
      - run: cat storage/testing.sqlite
      - run: php artisan serve &
      - run: ./vendor/bin/phpunit
  build2:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    <<: *defaults
    steps:
      - checkout
      - run: java -version
      - run: wget 127.0.1/login
      - run: unzip jmeter/apache-jmeter-3.2.zip
      - run: ./apache-jmeter-3.2/bin/jmeter -n -t ./coco.jmx
      
workflows:
  version: 2
  btd:
    jobs:
      - build
      - build2:
          requires:
            - build
      