version: 2

jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: touch storage/testing.sqlite
      - run: touch database/database.sqlite
      - run: php artisan migrate --env=testing --database=sqlite --force
      - run: php artisan db:seed --env=testing --database=sqlite --force
      - run: cat database/database.sqlite
      - run: cat storage/testing.sqlite
      - run: ./vendor/bin/phpunit
      - run: unzip jmeter/apache-jmeter-3.2.zip
      - run: cd /tmp && wget http://download.oracle.com/otn-pub/java/jdk/8u74-b02/jdk-8u74-linux-x64.tar.gz\?AuthParam\=1458001079_a6c78c74b34d63befd53037da604746c
      - run: tar xzf jdk-8u74-linux-x64.tar.gz?AuthParam=1458001079_a6c78c74b34d63befd53037da604746c && sudo mv jdk1.8.0_74 /opt && cd /opt/jdk1.8.0_74/
      - run: sudo update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_91/bin/java 2 && sudo update-alternatives --config java // select version  && sudo update-alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_91/bin/jar 2
      - run: sudo update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_91/bin/javac 2  && sudo update-alternatives --set jar /opt/jdk1.8.0_91/bin/jar  && sudo update-alternatives --set javac /opt/jdk1.8.0_74/bin/javac
      - run: java -version
      - run: sudo update-alternatives --config java
      - run: ./apache-jmeter-3.2/bin/jmeter coco.jmx