version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:latest
      - image: circleci/php:latest
    working_directory: ~/laravel
    steps:
      - checkout
      - run: composer self-update
      - run: mysql --version
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: php artisan migrate
      - run: php artisan db:seed
      - run: php artisan ./vendor/bin/phpunit