version: 2

jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: touch storage/testing.sqlite
      - run: touch database/database.sqlite
      - run: cp .env.testing .env
      - run: php artisan migrate --env=testing --database=sqlite --force
      - run: php artisan db:seed --env=testing --database=sqlite --force
      - run: cat database/database.sqlite
      - run: cat storage/testing.sqlite
      - run: ./vendor/bin/phpunit
      - run: unzip jmeter/apache-jmeter-3.2.zip
      - run: sudo apt-get install default-jre
      - run: sudo apt-get install python-software-properties software-properties-common
      - run: sudo add-apt-repository ppa:webupd8team/java
      - run: sudo apt-get update
      - run: sudo apt-get install oracle-java8-installer
      - run: java -version
      - run: sudo update-alternatives --config java
      - run: ./apache-jmeter-3.2/bin/jmeter coco.jmx