version: 2
jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y php7.1-sqlite3 libsqlite3-dev
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: php artisan migrate
      - run: php artisan db:seed
      - run: php artisan ./vendor/bin/phpunit